# 開発環境用
spring.datasource.url=jdbc:postgresql://localhost:5432/academy_db
spring.datasource.username=miyabi
spring.datasource.password=password

# Flywayの設定 
spring.flyway.enabled=false

logging.level.org.springframework.security=DEBUG

