#共通　どの設定ファイルを使うか（開発用 or 本番用）
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}


# 共通の設定（変更しないもの）
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# アップロード保存先（環境変数 APP_UPLOAD_DIR があればそれを優先）
app.upload-dir=${APP_UPLOAD_DIR:${user.dir}/uploads}