# 開発環境用
#spring.datasource.url=jdbc:postgresql://localhost:5432/dev
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.flyway.enabled=false




# 開発環境用
spring.datasource.url=jdbc:postgresql://localhost:5432/academy_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=false
