# 本番環境用
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Flywayは本番では有効
spring.flyway.enabled=true

# デバッグ
logging.level.org.springframework=DEBUG
logging.level.com.spring=DEBUG

# 本番の保存先（環境で未指定なら /var/app/uploads を使う例）
app.upload-dir=${APP_UPLOAD_DIR:/var/app/uploads}
