# 開発環境用
spring.datasource.url=jdbc:postgresql://localhost:5432/academy_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Flywayの設定
spring.flyway.enabled=false

# Hibernateに方言を明示
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update