#共通　どの設定ファイルを使うか（開発用 or 本番用）
spring.profiles.active=dev



#下記後で消す

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

#Flyway を一時的に無効
#spring.flyway.enabled=false



# 固定値で確認
#spring.datasource.url=jdbc:postgresql://db:5432/dev
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.flyway.enabled=false
