# 開発環境用
spring.datasource.url=jdbc:postgresql://localhost:5432/academy_db
spring.datasource.username=miyabi
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Flywayの設定
spring.flyway.enabled=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
